#!/bin/bash

echo `date`: Starting $0

scriptpath=$(readlink -f -- "$0";)
directory=$(dirname -- "$scriptpath")

cd "${directory}/.."

if [ -f run-update.lock ] ; then
    echo "Update in progress:"
    ls -l run-update.lock
    echo "Skipping update."
    exit 1
fi

touch run-update.lock

trap "rm run-update.lock" EXIT

source ../env/bin/activate

./Scripts/update-if-new-data

echo `date`: $0 completed
