#!/bin/bash

# Script for updating data and analyses.  After pulling and merging,
# it will regenerate the history & update the notebooks.

# First, pull and merge latest data first, as in:
#    git fetch --all -p
#    git merge nychealth/master

# Then run this script

# Generate history file
Scripts/regenerate-history

# Update analyses
Scripts/update-notebooks
